package chat;


/**
* chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, 13 February 2019 at 18:22:16 Greenwich Mean Time
*/

public interface ChatClientOperations 
{
  void update (String name, String text);
} // interface ChatClientOperations
