package chat;


/**
* chat/NameAlreadyUsed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, 13 February 2019 at 18:22:16 Greenwich Mean Time
*/

public final class NameAlreadyUsed extends org.omg.CORBA.UserException
{

  public NameAlreadyUsed ()
  {
    super(NameAlreadyUsedHelper.id());
  } // ctor


  public NameAlreadyUsed (String $reason)
  {
    super(NameAlreadyUsedHelper.id() + "  " + $reason);
  } // ctor

} // class NameAlreadyUsed
