package chat;


/**
* chat/UnknownID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Wednesday, 13 February 2019 at 18:22:16 Greenwich Mean Time
*/

public final class UnknownID extends org.omg.CORBA.UserException
{

  public UnknownID ()
  {
    super(UnknownIDHelper.id());
  } // ctor


  public UnknownID (String $reason)
  {
    super(UnknownIDHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownID
